# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q7zNeQ8GGcKWttDH0tdXTozhGRZSaS5s
"""

obj1 = Rector("[Nombre]", "[Apellido]", "[edad]")
obj2 = Alumno("[Nombre alumno]", "[Apellido alumno]", "[edad]", "[Colegio]", "[Año]")
obj3 = Profesor("[Nombre Profesor]", "[Apellido Profesor]","[Edad]", "[Institución]", "[Año]")
obj4 = auxiliar("[Nombre Auxiliar]", "[Apellido Auxiliar]", "[Edad]", "[Funcion]", "[Años de experiencia]")
obj5 =Alumni("[Nombre Alumni]", "[Apellido Alumni]", "[Edad]","[Nombre colegio]","[Año]","[des/empleado]","[Año egreso]")

class Rector:
  def __init__(self, nombre, apellido, edad):
    self.nombre = nombre
    self.apellido = apellido
    self.edad = edad
  def __str__(self):
    return("Saludos cordiales, soy "+ self.nombre+ " " +self.apellido+" el rector de la escuela y tengo " +str(self.edad) +" años.")
class Alumno(Rector):
  def __init__(self, nombre, apellido, edad, colegio, año):
    super().__init__(nombre, apellido, edad)
    self.colegioegreso = colegio
    self.añoingreso = año
  def set_nombre(self,nuevo_nombre):
    self.nombre = nuevo_nombre
  def get_nombre(self):
    return self.nombre
  def __str__(self):
    return("Tu eres " +self.nombre + " "+ self.apellido+ " tienes " +str(self.edad)
  + " saliste de la insitucion " +self.colegioegreso+ " e ingresaste a la carrera en el año " +str(self.añoingreso)+".")
class Profesor(Rector):
  def __init__(self, nombre, apellido, edad, añosestudio, institucionegreso):
    super().__init__(nombre, apellido, edad)
    self.año= añosestudio
    self.insti= institucionegreso
  def get_edad(self):
    return self.edad
  def set_edad(self, nueva_edad):
    self.nombre = nueva_edad
  def __str__(self):
    return("Bienvenido estimado " +self.nombre + " "+ self.apellido+ " de" +str(self.edad)+ "de edad, " + 
"docente en el area de Telecomunicaciones, el cual estudio durante "+str(self.año) +" en la prestigiosa universidad "+ self.insti ) 
class auxiliar(Rector):
  def __init__(self, nombre, apellido, edad, funcion, añosexperiencia):
    super().__init__(nombre, apellido, edad)
    self.funcion = funcion
    self.exp = añosexperiencia
  def get_edad(self):
    return self.edad
  def __str__(self):
    return("Tu eres " +self.nombre + " "+ self.apellido+ " tienes " +str(self.edad)+ " , tu funcion es  " +self.funcion 
  + " y tienes " +str(self.exp)+" años de experiencia.")

class Alumni(Alumno):
  def __init__(self, nombre, apellido, edad, colegio, año, empleo, egreso):
    super().__init__( nombre, apellido, edad, colegio, año)
    self.empleado= empleo 
    self.añoegreso= egreso
  def get_egreso(self):
    return self.añoegreso
  def __str__(self):
    return("Bienvenido al portal "+self.nombre +" "+ self.apellido+ " de " +self.edad
+ " años, sus caracteristicas importantes son: Egresaste del colegio "+self.colegioegreso 
+" el año "+str(self.añoingreso) +", luego, entraste a esta universidad, en la cual te graduaste el año "+str(self.añoegreso)  
+ " y ahora te encuentras "+self.empleado)

print(obj1)
print(obj2)
print(obj5.get_egreso())